// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/asset/asset.proto

package asset

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResultStatus int32

const (
	ResultStatus_Success     ResultStatus = 0
	ResultStatus_MaxLimit    ResultStatus = 1
	ResultStatus_Repeated    ResultStatus = 2
	ResultStatus_NotExisted  ResultStatus = 3
	ResultStatus_DBException ResultStatus = 4
	ResultStatus_Empty       ResultStatus = 5
)

var ResultStatus_name = map[int32]string{
	0: "Success",
	1: "MaxLimit",
	2: "Repeated",
	3: "NotExisted",
	4: "DBException",
	5: "Empty",
}

var ResultStatus_value = map[string]int32{
	"Success":     0,
	"MaxLimit":    1,
	"Repeated":    2,
	"NotExisted":  3,
	"DBException": 4,
	"Empty":       5,
}

func (x ResultStatus) String() string {
	return proto.EnumName(ResultStatus_name, int32(x))
}

func (ResultStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_78e4568551c90fa4, []int{0}
}

type OwnerType int32

const (
	OwnerType_Single OwnerType = 0
	OwnerType_Group  OwnerType = 1
)

var OwnerType_name = map[int32]string{
	0: "Single",
	1: "Group",
}

var OwnerType_value = map[string]int32{
	"Single": 0,
	"Group":  1,
}

func (x OwnerType) String() string {
	return proto.EnumName(OwnerType_name, int32(x))
}

func (OwnerType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_78e4568551c90fa4, []int{1}
}

type RequestInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Operator             string   `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestInfo) Reset()         { *m = RequestInfo{} }
func (m *RequestInfo) String() string { return proto.CompactTextString(m) }
func (*RequestInfo) ProtoMessage()    {}
func (*RequestInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_78e4568551c90fa4, []int{0}
}

func (m *RequestInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestInfo.Unmarshal(m, b)
}
func (m *RequestInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestInfo.Marshal(b, m, deterministic)
}
func (m *RequestInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestInfo.Merge(m, src)
}
func (m *RequestInfo) XXX_Size() int {
	return xxx_messageInfo_RequestInfo.Size(m)
}
func (m *RequestInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RequestInfo proto.InternalMessageInfo

func (m *RequestInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *RequestInfo) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *RequestInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

type AssetInfo struct {
	Uid                  string    `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Md5                  string    `protobuf:"bytes,3,opt,name=md5,proto3" json:"md5,omitempty"`
	Format               string    `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	Version              string    `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Size                 uint64    `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	Language             string    `protobuf:"bytes,7,opt,name=language,proto3" json:"language,omitempty"`
	Type                 OwnerType `protobuf:"varint,8,opt,name=type,proto3,enum=omo.msp.asset.OwnerType" json:"type,omitempty"`
	Owner                string    `protobuf:"bytes,9,opt,name=owner,proto3" json:"owner,omitempty"`
	Uuid                 string    `protobuf:"bytes,10,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Created              int64     `protobuf:"varint,11,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64     `protobuf:"varint,12,opt,name=updated,proto3" json:"updated,omitempty"`
	Creator              string    `protobuf:"bytes,13,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string    `protobuf:"bytes,14,opt,name=operator,proto3" json:"operator,omitempty"`
	Width                uint32    `protobuf:"varint,15,opt,name=width,proto3" json:"width,omitempty"`
	Height               uint32    `protobuf:"varint,16,opt,name=height,proto3" json:"height,omitempty"`
	Snapshot             string    `protobuf:"bytes,17,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Thumbs               []string  `protobuf:"bytes,18,rep,name=thumbs,proto3" json:"thumbs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AssetInfo) Reset()         { *m = AssetInfo{} }
func (m *AssetInfo) String() string { return proto.CompactTextString(m) }
func (*AssetInfo) ProtoMessage()    {}
func (*AssetInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_78e4568551c90fa4, []int{1}
}

func (m *AssetInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssetInfo.Unmarshal(m, b)
}
func (m *AssetInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssetInfo.Marshal(b, m, deterministic)
}
func (m *AssetInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetInfo.Merge(m, src)
}
func (m *AssetInfo) XXX_Size() int {
	return xxx_messageInfo_AssetInfo.Size(m)
}
func (m *AssetInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AssetInfo proto.InternalMessageInfo

func (m *AssetInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *AssetInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AssetInfo) GetMd5() string {
	if m != nil {
		return m.Md5
	}
	return ""
}

func (m *AssetInfo) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *AssetInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *AssetInfo) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *AssetInfo) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *AssetInfo) GetType() OwnerType {
	if m != nil {
		return m.Type
	}
	return OwnerType_Single
}

func (m *AssetInfo) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *AssetInfo) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *AssetInfo) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *AssetInfo) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *AssetInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *AssetInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *AssetInfo) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *AssetInfo) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *AssetInfo) GetSnapshot() string {
	if m != nil {
		return m.Snapshot
	}
	return ""
}

func (m *AssetInfo) GetThumbs() []string {
	if m != nil {
		return m.Thumbs
	}
	return nil
}

type ReplyStatus struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplyStatus) Reset()         { *m = ReplyStatus{} }
func (m *ReplyStatus) String() string { return proto.CompactTextString(m) }
func (*ReplyStatus) ProtoMessage()    {}
func (*ReplyStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_78e4568551c90fa4, []int{2}
}

func (m *ReplyStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyStatus.Unmarshal(m, b)
}
func (m *ReplyStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyStatus.Marshal(b, m, deterministic)
}
func (m *ReplyStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyStatus.Merge(m, src)
}
func (m *ReplyStatus) XXX_Size() int {
	return xxx_messageInfo_ReplyStatus.Size(m)
}
func (m *ReplyStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyStatus proto.InternalMessageInfo

func (m *ReplyStatus) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ReplyStatus) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ReplyInfo struct {
	Uid                  string       `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyInfo) Reset()         { *m = ReplyInfo{} }
func (m *ReplyInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyInfo) ProtoMessage()    {}
func (*ReplyInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_78e4568551c90fa4, []int{3}
}

func (m *ReplyInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyInfo.Unmarshal(m, b)
}
func (m *ReplyInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyInfo.Marshal(b, m, deterministic)
}
func (m *ReplyInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyInfo.Merge(m, src)
}
func (m *ReplyInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyInfo.Size(m)
}
func (m *ReplyInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyInfo proto.InternalMessageInfo

func (m *ReplyInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReplyInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ReqAssetAdd struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Md5                  string    `protobuf:"bytes,2,opt,name=md5,proto3" json:"md5,omitempty"`
	Format               string    `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	Version              string    `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Size                 uint64    `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	Language             string    `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	Uuid                 string    `protobuf:"bytes,7,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Owner                string    `protobuf:"bytes,8,opt,name=owner,proto3" json:"owner,omitempty"`
	Type                 OwnerType `protobuf:"varint,9,opt,name=type,proto3,enum=omo.msp.asset.OwnerType" json:"type,omitempty"`
	Operator             string    `protobuf:"bytes,10,opt,name=operator,proto3" json:"operator,omitempty"`
	Width                uint32    `protobuf:"varint,11,opt,name=width,proto3" json:"width,omitempty"`
	Height               uint32    `protobuf:"varint,12,opt,name=height,proto3" json:"height,omitempty"`
	Snapshot             string    `protobuf:"bytes,13,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Thumbs               []string  `protobuf:"bytes,14,rep,name=thumbs,proto3" json:"thumbs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ReqAssetAdd) Reset()         { *m = ReqAssetAdd{} }
func (m *ReqAssetAdd) String() string { return proto.CompactTextString(m) }
func (*ReqAssetAdd) ProtoMessage()    {}
func (*ReqAssetAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_78e4568551c90fa4, []int{4}
}

func (m *ReqAssetAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqAssetAdd.Unmarshal(m, b)
}
func (m *ReqAssetAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqAssetAdd.Marshal(b, m, deterministic)
}
func (m *ReqAssetAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqAssetAdd.Merge(m, src)
}
func (m *ReqAssetAdd) XXX_Size() int {
	return xxx_messageInfo_ReqAssetAdd.Size(m)
}
func (m *ReqAssetAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqAssetAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqAssetAdd proto.InternalMessageInfo

func (m *ReqAssetAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqAssetAdd) GetMd5() string {
	if m != nil {
		return m.Md5
	}
	return ""
}

func (m *ReqAssetAdd) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *ReqAssetAdd) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ReqAssetAdd) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ReqAssetAdd) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *ReqAssetAdd) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ReqAssetAdd) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReqAssetAdd) GetType() OwnerType {
	if m != nil {
		return m.Type
	}
	return OwnerType_Single
}

func (m *ReqAssetAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqAssetAdd) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *ReqAssetAdd) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ReqAssetAdd) GetSnapshot() string {
	if m != nil {
		return m.Snapshot
	}
	return ""
}

func (m *ReqAssetAdd) GetThumbs() []string {
	if m != nil {
		return m.Thumbs
	}
	return nil
}

type ReqAssetSnapshot struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Snapshot             string   `protobuf:"bytes,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqAssetSnapshot) Reset()         { *m = ReqAssetSnapshot{} }
func (m *ReqAssetSnapshot) String() string { return proto.CompactTextString(m) }
func (*ReqAssetSnapshot) ProtoMessage()    {}
func (*ReqAssetSnapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_78e4568551c90fa4, []int{5}
}

func (m *ReqAssetSnapshot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqAssetSnapshot.Unmarshal(m, b)
}
func (m *ReqAssetSnapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqAssetSnapshot.Marshal(b, m, deterministic)
}
func (m *ReqAssetSnapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqAssetSnapshot.Merge(m, src)
}
func (m *ReqAssetSnapshot) XXX_Size() int {
	return xxx_messageInfo_ReqAssetSnapshot.Size(m)
}
func (m *ReqAssetSnapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqAssetSnapshot.DiscardUnknown(m)
}

var xxx_messageInfo_ReqAssetSnapshot proto.InternalMessageInfo

func (m *ReqAssetSnapshot) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqAssetSnapshot) GetSnapshot() string {
	if m != nil {
		return m.Snapshot
	}
	return ""
}

type ReqAssetThumbs struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Thumbs               []string `protobuf:"bytes,2,rep,name=thumbs,proto3" json:"thumbs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqAssetThumbs) Reset()         { *m = ReqAssetThumbs{} }
func (m *ReqAssetThumbs) String() string { return proto.CompactTextString(m) }
func (*ReqAssetThumbs) ProtoMessage()    {}
func (*ReqAssetThumbs) Descriptor() ([]byte, []int) {
	return fileDescriptor_78e4568551c90fa4, []int{6}
}

func (m *ReqAssetThumbs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqAssetThumbs.Unmarshal(m, b)
}
func (m *ReqAssetThumbs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqAssetThumbs.Marshal(b, m, deterministic)
}
func (m *ReqAssetThumbs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqAssetThumbs.Merge(m, src)
}
func (m *ReqAssetThumbs) XXX_Size() int {
	return xxx_messageInfo_ReqAssetThumbs.Size(m)
}
func (m *ReqAssetThumbs) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqAssetThumbs.DiscardUnknown(m)
}

var xxx_messageInfo_ReqAssetThumbs proto.InternalMessageInfo

func (m *ReqAssetThumbs) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqAssetThumbs) GetThumbs() []string {
	if m != nil {
		return m.Thumbs
	}
	return nil
}

type ReplyAssetOne struct {
	Info                 *AssetInfo   `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyAssetOne) Reset()         { *m = ReplyAssetOne{} }
func (m *ReplyAssetOne) String() string { return proto.CompactTextString(m) }
func (*ReplyAssetOne) ProtoMessage()    {}
func (*ReplyAssetOne) Descriptor() ([]byte, []int) {
	return fileDescriptor_78e4568551c90fa4, []int{7}
}

func (m *ReplyAssetOne) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyAssetOne.Unmarshal(m, b)
}
func (m *ReplyAssetOne) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyAssetOne.Marshal(b, m, deterministic)
}
func (m *ReplyAssetOne) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyAssetOne.Merge(m, src)
}
func (m *ReplyAssetOne) XXX_Size() int {
	return xxx_messageInfo_ReplyAssetOne.Size(m)
}
func (m *ReplyAssetOne) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyAssetOne.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyAssetOne proto.InternalMessageInfo

func (m *ReplyAssetOne) GetInfo() *AssetInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ReplyAssetOne) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ReqAssetList struct {
	List                 []string `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqAssetList) Reset()         { *m = ReqAssetList{} }
func (m *ReqAssetList) String() string { return proto.CompactTextString(m) }
func (*ReqAssetList) ProtoMessage()    {}
func (*ReqAssetList) Descriptor() ([]byte, []int) {
	return fileDescriptor_78e4568551c90fa4, []int{8}
}

func (m *ReqAssetList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqAssetList.Unmarshal(m, b)
}
func (m *ReqAssetList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqAssetList.Marshal(b, m, deterministic)
}
func (m *ReqAssetList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqAssetList.Merge(m, src)
}
func (m *ReqAssetList) XXX_Size() int {
	return xxx_messageInfo_ReqAssetList.Size(m)
}
func (m *ReqAssetList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqAssetList.DiscardUnknown(m)
}

var xxx_messageInfo_ReqAssetList proto.InternalMessageInfo

func (m *ReqAssetList) GetList() []string {
	if m != nil {
		return m.List
	}
	return nil
}

type ReplyAssetList struct {
	Owner                string       `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	List                 []*AssetInfo `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyAssetList) Reset()         { *m = ReplyAssetList{} }
func (m *ReplyAssetList) String() string { return proto.CompactTextString(m) }
func (*ReplyAssetList) ProtoMessage()    {}
func (*ReplyAssetList) Descriptor() ([]byte, []int) {
	return fileDescriptor_78e4568551c90fa4, []int{9}
}

func (m *ReplyAssetList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyAssetList.Unmarshal(m, b)
}
func (m *ReplyAssetList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyAssetList.Marshal(b, m, deterministic)
}
func (m *ReplyAssetList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyAssetList.Merge(m, src)
}
func (m *ReplyAssetList) XXX_Size() int {
	return xxx_messageInfo_ReplyAssetList.Size(m)
}
func (m *ReplyAssetList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyAssetList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyAssetList proto.InternalMessageInfo

func (m *ReplyAssetList) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReplyAssetList) GetList() []*AssetInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *ReplyAssetList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterEnum("omo.msp.asset.ResultStatus", ResultStatus_name, ResultStatus_value)
	proto.RegisterEnum("omo.msp.asset.OwnerType", OwnerType_name, OwnerType_value)
	proto.RegisterType((*RequestInfo)(nil), "omo.msp.asset.RequestInfo")
	proto.RegisterType((*AssetInfo)(nil), "omo.msp.asset.AssetInfo")
	proto.RegisterType((*ReplyStatus)(nil), "omo.msp.asset.ReplyStatus")
	proto.RegisterType((*ReplyInfo)(nil), "omo.msp.asset.ReplyInfo")
	proto.RegisterType((*ReqAssetAdd)(nil), "omo.msp.asset.ReqAssetAdd")
	proto.RegisterType((*ReqAssetSnapshot)(nil), "omo.msp.asset.ReqAssetSnapshot")
	proto.RegisterType((*ReqAssetThumbs)(nil), "omo.msp.asset.ReqAssetThumbs")
	proto.RegisterType((*ReplyAssetOne)(nil), "omo.msp.asset.ReplyAssetOne")
	proto.RegisterType((*ReqAssetList)(nil), "omo.msp.asset.ReqAssetList")
	proto.RegisterType((*ReplyAssetList)(nil), "omo.msp.asset.ReplyAssetList")
}

func init() {
	proto.RegisterFile("proto/asset/asset.proto", fileDescriptor_78e4568551c90fa4)
}

var fileDescriptor_78e4568551c90fa4 = []byte{
	// 798 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xcd, 0x8e, 0xe3, 0x44,
	0x10, 0x8e, 0x63, 0xe7, 0xaf, 0x9c, 0x64, 0x4d, 0x0b, 0x41, 0x2b, 0xb0, 0x22, 0xf2, 0x29, 0x5a,
	0xa1, 0x20, 0x05, 0x21, 0x24, 0x4e, 0xcc, 0xb0, 0xa3, 0x68, 0xa5, 0x5d, 0x46, 0xeb, 0x2c, 0x17,
	0x6e, 0xde, 0xb8, 0x27, 0xb1, 0x14, 0xbb, 0xbd, 0xee, 0xf6, 0xcc, 0x84, 0x27, 0xe0, 0xc2, 0x83,
	0xf1, 0x2c, 0xbc, 0x04, 0xaa, 0xf2, 0xcf, 0x38, 0x93, 0x38, 0x33, 0xda, 0x4b, 0xd4, 0x5f, 0x57,
	0xf5, 0xe7, 0xaa, 0xfa, 0xbe, 0xb6, 0x03, 0x5f, 0x27, 0xa9, 0xd4, 0xf2, 0x07, 0x5f, 0x29, 0xa1,
	0xf3, 0xdf, 0x39, 0xed, 0xb0, 0x91, 0x8c, 0xe4, 0x3c, 0x52, 0xc9, 0x9c, 0x36, 0xdd, 0xf7, 0x60,
	0x7b, 0xe2, 0x53, 0x26, 0x94, 0x7e, 0x13, 0xdf, 0x48, 0xe6, 0x80, 0x99, 0x85, 0x01, 0x37, 0xa6,
	0xc6, 0x6c, 0xe0, 0xe1, 0x92, 0x7d, 0x09, 0x1d, 0x79, 0x17, 0x8b, 0x94, 0xb7, 0x69, 0x2f, 0x07,
	0x6c, 0x02, 0x7d, 0x99, 0x88, 0xd4, 0xd7, 0x32, 0xe5, 0x26, 0x05, 0x2a, 0xec, 0xfe, 0x6b, 0xc2,
	0xe0, 0x02, 0xc9, 0x1b, 0x18, 0x19, 0x58, 0xb1, 0x1f, 0x89, 0x82, 0x90, 0xd6, 0x98, 0x15, 0x05,
	0x3f, 0x15, 0x54, 0xb8, 0x64, 0x5f, 0x41, 0xf7, 0x46, 0xa6, 0x91, 0xaf, 0xb9, 0x45, 0x9b, 0x05,
	0x62, 0x1c, 0x7a, 0xb7, 0x22, 0x55, 0xa1, 0x8c, 0x79, 0x87, 0x02, 0x25, 0x44, 0x5e, 0x15, 0xfe,
	0x25, 0x78, 0x77, 0x6a, 0xcc, 0x2c, 0x8f, 0xd6, 0x58, 0xe7, 0xce, 0x8f, 0x37, 0x99, 0xbf, 0x11,
	0xbc, 0x97, 0xd7, 0x59, 0x62, 0xf6, 0x3d, 0x58, 0x7a, 0x9f, 0x08, 0xde, 0x9f, 0x1a, 0xb3, 0xf1,
	0x82, 0xcf, 0x0f, 0x06, 0x33, 0xbf, 0xc6, 0x3e, 0x3f, 0xec, 0x13, 0xe1, 0x51, 0xd6, 0xc3, 0x1c,
	0x06, 0xf5, 0x39, 0x30, 0xb0, 0x32, 0x6c, 0x0f, 0xf2, 0x5e, 0x70, 0x8d, 0x15, 0xae, 0x53, 0xe1,
	0x6b, 0x11, 0x70, 0x7b, 0x6a, 0xcc, 0x4c, 0xaf, 0x84, 0x18, 0xc9, 0x92, 0x80, 0x22, 0xc3, 0x3c,
	0x52, 0xc0, 0xea, 0x8c, 0x4c, 0xf9, 0x28, 0xef, 0xaa, 0x80, 0x07, 0x93, 0x1e, 0x1f, 0x4e, 0x1a,
	0x6b, 0xba, 0x0b, 0x03, 0xbd, 0xe5, 0x2f, 0xa6, 0xc6, 0x6c, 0xe4, 0xe5, 0x00, 0x27, 0xb7, 0x15,
	0xe1, 0x66, 0xab, 0xb9, 0x43, 0xdb, 0x05, 0x42, 0x26, 0x15, 0xfb, 0x89, 0xda, 0x4a, 0xcd, 0xbf,
	0xc8, 0x99, 0x4a, 0x8c, 0x67, 0xf4, 0x36, 0x8b, 0x3e, 0x2a, 0xce, 0xa6, 0x26, 0x4e, 0x3b, 0x47,
	0xee, 0xcf, 0x68, 0x8f, 0x64, 0xb7, 0x5f, 0x69, 0x5f, 0x67, 0x0a, 0xdb, 0x5d, 0xcb, 0x40, 0x90,
	0x9a, 0x23, 0x8f, 0xd6, 0x58, 0x84, 0x48, 0x53, 0x59, 0x19, 0x84, 0x80, 0xfb, 0x1e, 0x06, 0x74,
	0xb0, 0xc1, 0x03, 0x0b, 0xe8, 0x2a, 0xa2, 0xa4, 0x53, 0xf6, 0x62, 0xf2, 0x68, 0xfa, 0xb5, 0x87,
	0x7a, 0x45, 0xa6, 0xfb, 0x5f, 0x9b, 0xbc, 0x4a, 0xd6, 0xba, 0x08, 0x1e, 0x7c, 0x64, 0x1c, 0xfb,
	0xa8, 0x7d, 0xca, 0x47, 0x66, 0x93, 0x8f, 0xac, 0xd3, 0x3e, 0xea, 0x34, 0xf8, 0xa8, 0xfb, 0xc8,
	0x47, 0xa5, 0x07, 0x7a, 0x35, 0x0f, 0x54, 0x6e, 0xe9, 0xd7, 0xdd, 0x52, 0x3a, 0x6e, 0xf0, 0x2c,
	0xc7, 0xd5, 0x95, 0x87, 0x26, 0xe5, 0xed, 0xd3, 0xca, 0x0f, 0x1b, 0x95, 0x1f, 0x35, 0x2a, 0x3f,
	0x3e, 0x50, 0xfe, 0x57, 0x70, 0xca, 0x61, 0xaf, 0xca, 0xdc, 0x63, 0x1d, 0xeb, 0xcc, 0xed, 0x43,
	0x66, 0xf7, 0x17, 0x18, 0x97, 0x0c, 0x1f, 0x88, 0xf3, 0xc4, 0xf9, 0x87, 0xa7, 0xb7, 0x0f, 0x9e,
	0xfe, 0x09, 0x46, 0x64, 0x01, 0x3a, 0x7d, 0x1d, 0xd3, 0x65, 0x0d, 0xe3, 0x1b, 0x49, 0x67, 0xed,
	0xa3, 0xd1, 0x55, 0xaf, 0x1b, 0x8f, 0xb2, 0x3e, 0xcb, 0x5e, 0x2e, 0x0c, 0xcb, 0x72, 0xdf, 0x86,
	0x4a, 0xa3, 0xac, 0xbb, 0x50, 0x69, 0x6e, 0x50, 0x61, 0xb4, 0x76, 0xff, 0x36, 0xb0, 0xa7, 0xb2,
	0x2e, 0x4a, 0xab, 0x94, 0x36, 0x1e, 0x29, 0x4d, 0x87, 0xb1, 0xab, 0xb3, 0xe5, 0x62, 0x56, 0xad,
	0x5c, 0xf3, 0xb9, 0xe5, 0xbe, 0x5a, 0x63, 0xb9, 0x2a, 0xdb, 0xe9, 0xe2, 0x6a, 0xda, 0xd0, 0x5b,
	0x65, 0xeb, 0xb5, 0x50, 0xca, 0x69, 0xb1, 0x21, 0xf4, 0xdf, 0xf9, 0xf7, 0x6f, 0xc3, 0x28, 0xd4,
	0x8e, 0x81, 0xc8, 0x13, 0x09, 0xbd, 0x82, 0x9c, 0x36, 0x1b, 0x03, 0xfc, 0x2e, 0xf5, 0xd5, 0x7d,
	0xa8, 0x10, 0x9b, 0xec, 0x05, 0xd8, 0xaf, 0x2f, 0xaf, 0xee, 0xd7, 0x22, 0xd1, 0xa1, 0x8c, 0x1d,
	0x8b, 0x0d, 0xa0, 0x73, 0x15, 0x25, 0x7a, 0xef, 0x74, 0x5e, 0xb9, 0x30, 0xa8, 0x5c, 0xc9, 0x00,
	0xba, 0xab, 0x30, 0xde, 0xec, 0x84, 0xd3, 0xc2, 0x9c, 0x65, 0x2a, 0xb3, 0xc4, 0x31, 0x16, 0xff,
	0x58, 0x30, 0xcc, 0x6d, 0x22, 0xd2, 0xdb, 0x70, 0x2d, 0xd8, 0x6b, 0xe8, 0x5e, 0x04, 0x01, 0x8a,
	0x76, 0xdc, 0x47, 0x75, 0x7b, 0x27, 0xdf, 0x9e, 0xea, 0xb1, 0x94, 0xdb, 0x6d, 0x21, 0xcb, 0x32,
	0x97, 0xfe, 0x04, 0x4b, 0xf9, 0xbd, 0x7a, 0x92, 0xe5, 0x37, 0x7c, 0x0d, 0x45, 0xf2, 0x56, 0x3c,
	0x45, 0xc4, 0x4f, 0x11, 0x61, 0xc4, 0x6d, 0xb1, 0x25, 0xf4, 0x96, 0x85, 0xda, 0xdf, 0x34, 0x74,
	0x84, 0xc1, 0xc9, 0xcb, 0xc6, 0x62, 0x30, 0xec, 0xb6, 0xd8, 0x1b, 0x80, 0xa5, 0xd0, 0x97, 0xfb,
	0xeb, 0xfc, 0x1b, 0x7a, 0xa6, 0x9c, 0x67, 0x50, 0x0d, 0xff, 0xa0, 0x6f, 0x47, 0x71, 0xb5, 0x5e,
	0x36, 0x14, 0x96, 0x87, 0xcf, 0xb6, 0xf7, 0x0e, 0xc6, 0x39, 0x55, 0x75, 0xcf, 0xbf, 0x6b, 0x20,
	0x2b, 0x13, 0xce, 0xd1, 0x5d, 0x8e, 0xfe, 0xb4, 0x6b, 0xff, 0x3d, 0x3e, 0x76, 0x09, 0xfc, 0xf8,
	0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbc, 0x66, 0xea, 0x84, 0x91, 0x08, 0x00, 0x00,
}
