// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/asset/asset.proto

package asset

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OwnerType int32

const (
	OwnerType_Single OwnerType = 0
	OwnerType_Group  OwnerType = 1
)

var OwnerType_name = map[int32]string{
	0: "Single",
	1: "Group",
}

var OwnerType_value = map[string]int32{
	"Single": 0,
	"Group":  1,
}

func (x OwnerType) String() string {
	return proto.EnumName(OwnerType_name, int32(x))
}

func (OwnerType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_78e4568551c90fa4, []int{0}
}

type AssetInfo struct {
	Uid                  string    `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Md5                  string    `protobuf:"bytes,3,opt,name=md5,proto3" json:"md5,omitempty"`
	Format               string    `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	Version              string    `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Size                 uint64    `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	Language             string    `protobuf:"bytes,7,opt,name=language,proto3" json:"language,omitempty"`
	Type                 OwnerType `protobuf:"varint,8,opt,name=type,proto3,enum=omo.msp.asset.OwnerType" json:"type,omitempty"`
	Owner                string    `protobuf:"bytes,9,opt,name=owner,proto3" json:"owner,omitempty"`
	Uuid                 string    `protobuf:"bytes,10,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Created              int64     `protobuf:"varint,11,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64     `protobuf:"varint,12,opt,name=updated,proto3" json:"updated,omitempty"`
	Creator              string    `protobuf:"bytes,13,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string    `protobuf:"bytes,14,opt,name=operator,proto3" json:"operator,omitempty"`
	Width                uint32    `protobuf:"varint,15,opt,name=width,proto3" json:"width,omitempty"`
	Height               uint32    `protobuf:"varint,16,opt,name=height,proto3" json:"height,omitempty"`
	Snapshot             string    `protobuf:"bytes,17,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Thumbs               []string  `protobuf:"bytes,18,rep,name=thumbs,proto3" json:"thumbs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AssetInfo) Reset()         { *m = AssetInfo{} }
func (m *AssetInfo) String() string { return proto.CompactTextString(m) }
func (*AssetInfo) ProtoMessage()    {}
func (*AssetInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_78e4568551c90fa4, []int{0}
}

func (m *AssetInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssetInfo.Unmarshal(m, b)
}
func (m *AssetInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssetInfo.Marshal(b, m, deterministic)
}
func (m *AssetInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetInfo.Merge(m, src)
}
func (m *AssetInfo) XXX_Size() int {
	return xxx_messageInfo_AssetInfo.Size(m)
}
func (m *AssetInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AssetInfo proto.InternalMessageInfo

func (m *AssetInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *AssetInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AssetInfo) GetMd5() string {
	if m != nil {
		return m.Md5
	}
	return ""
}

func (m *AssetInfo) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *AssetInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *AssetInfo) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *AssetInfo) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *AssetInfo) GetType() OwnerType {
	if m != nil {
		return m.Type
	}
	return OwnerType_Single
}

func (m *AssetInfo) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *AssetInfo) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *AssetInfo) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *AssetInfo) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *AssetInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *AssetInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *AssetInfo) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *AssetInfo) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *AssetInfo) GetSnapshot() string {
	if m != nil {
		return m.Snapshot
	}
	return ""
}

func (m *AssetInfo) GetThumbs() []string {
	if m != nil {
		return m.Thumbs
	}
	return nil
}

type ReqAssetAdd struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Md5                  string    `protobuf:"bytes,2,opt,name=md5,proto3" json:"md5,omitempty"`
	Format               string    `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	Version              string    `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Size                 uint64    `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	Language             string    `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	Uuid                 string    `protobuf:"bytes,7,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Owner                string    `protobuf:"bytes,8,opt,name=owner,proto3" json:"owner,omitempty"`
	Type                 OwnerType `protobuf:"varint,9,opt,name=type,proto3,enum=omo.msp.asset.OwnerType" json:"type,omitempty"`
	Operator             string    `protobuf:"bytes,10,opt,name=operator,proto3" json:"operator,omitempty"`
	Width                uint32    `protobuf:"varint,11,opt,name=width,proto3" json:"width,omitempty"`
	Height               uint32    `protobuf:"varint,12,opt,name=height,proto3" json:"height,omitempty"`
	Snapshot             string    `protobuf:"bytes,13,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Thumbs               []string  `protobuf:"bytes,14,rep,name=thumbs,proto3" json:"thumbs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ReqAssetAdd) Reset()         { *m = ReqAssetAdd{} }
func (m *ReqAssetAdd) String() string { return proto.CompactTextString(m) }
func (*ReqAssetAdd) ProtoMessage()    {}
func (*ReqAssetAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_78e4568551c90fa4, []int{1}
}

func (m *ReqAssetAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqAssetAdd.Unmarshal(m, b)
}
func (m *ReqAssetAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqAssetAdd.Marshal(b, m, deterministic)
}
func (m *ReqAssetAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqAssetAdd.Merge(m, src)
}
func (m *ReqAssetAdd) XXX_Size() int {
	return xxx_messageInfo_ReqAssetAdd.Size(m)
}
func (m *ReqAssetAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqAssetAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqAssetAdd proto.InternalMessageInfo

func (m *ReqAssetAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqAssetAdd) GetMd5() string {
	if m != nil {
		return m.Md5
	}
	return ""
}

func (m *ReqAssetAdd) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *ReqAssetAdd) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ReqAssetAdd) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ReqAssetAdd) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *ReqAssetAdd) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ReqAssetAdd) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReqAssetAdd) GetType() OwnerType {
	if m != nil {
		return m.Type
	}
	return OwnerType_Single
}

func (m *ReqAssetAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqAssetAdd) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *ReqAssetAdd) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ReqAssetAdd) GetSnapshot() string {
	if m != nil {
		return m.Snapshot
	}
	return ""
}

func (m *ReqAssetAdd) GetThumbs() []string {
	if m != nil {
		return m.Thumbs
	}
	return nil
}

type ReqAssetSnapshot struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Snapshot             string   `protobuf:"bytes,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Operator             string   `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqAssetSnapshot) Reset()         { *m = ReqAssetSnapshot{} }
func (m *ReqAssetSnapshot) String() string { return proto.CompactTextString(m) }
func (*ReqAssetSnapshot) ProtoMessage()    {}
func (*ReqAssetSnapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_78e4568551c90fa4, []int{2}
}

func (m *ReqAssetSnapshot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqAssetSnapshot.Unmarshal(m, b)
}
func (m *ReqAssetSnapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqAssetSnapshot.Marshal(b, m, deterministic)
}
func (m *ReqAssetSnapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqAssetSnapshot.Merge(m, src)
}
func (m *ReqAssetSnapshot) XXX_Size() int {
	return xxx_messageInfo_ReqAssetSnapshot.Size(m)
}
func (m *ReqAssetSnapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqAssetSnapshot.DiscardUnknown(m)
}

var xxx_messageInfo_ReqAssetSnapshot proto.InternalMessageInfo

func (m *ReqAssetSnapshot) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqAssetSnapshot) GetSnapshot() string {
	if m != nil {
		return m.Snapshot
	}
	return ""
}

func (m *ReqAssetSnapshot) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

type ReplyAssetOne struct {
	Info                 *AssetInfo   `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyAssetOne) Reset()         { *m = ReplyAssetOne{} }
func (m *ReplyAssetOne) String() string { return proto.CompactTextString(m) }
func (*ReplyAssetOne) ProtoMessage()    {}
func (*ReplyAssetOne) Descriptor() ([]byte, []int) {
	return fileDescriptor_78e4568551c90fa4, []int{3}
}

func (m *ReplyAssetOne) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyAssetOne.Unmarshal(m, b)
}
func (m *ReplyAssetOne) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyAssetOne.Marshal(b, m, deterministic)
}
func (m *ReplyAssetOne) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyAssetOne.Merge(m, src)
}
func (m *ReplyAssetOne) XXX_Size() int {
	return xxx_messageInfo_ReplyAssetOne.Size(m)
}
func (m *ReplyAssetOne) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyAssetOne.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyAssetOne proto.InternalMessageInfo

func (m *ReplyAssetOne) GetInfo() *AssetInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ReplyAssetOne) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ReqAssetList struct {
	List                 []string `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqAssetList) Reset()         { *m = ReqAssetList{} }
func (m *ReqAssetList) String() string { return proto.CompactTextString(m) }
func (*ReqAssetList) ProtoMessage()    {}
func (*ReqAssetList) Descriptor() ([]byte, []int) {
	return fileDescriptor_78e4568551c90fa4, []int{4}
}

func (m *ReqAssetList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqAssetList.Unmarshal(m, b)
}
func (m *ReqAssetList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqAssetList.Marshal(b, m, deterministic)
}
func (m *ReqAssetList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqAssetList.Merge(m, src)
}
func (m *ReqAssetList) XXX_Size() int {
	return xxx_messageInfo_ReqAssetList.Size(m)
}
func (m *ReqAssetList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqAssetList.DiscardUnknown(m)
}

var xxx_messageInfo_ReqAssetList proto.InternalMessageInfo

func (m *ReqAssetList) GetList() []string {
	if m != nil {
		return m.List
	}
	return nil
}

type ReplyAssetList struct {
	Owner                string       `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	List                 []*AssetInfo `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyAssetList) Reset()         { *m = ReplyAssetList{} }
func (m *ReplyAssetList) String() string { return proto.CompactTextString(m) }
func (*ReplyAssetList) ProtoMessage()    {}
func (*ReplyAssetList) Descriptor() ([]byte, []int) {
	return fileDescriptor_78e4568551c90fa4, []int{5}
}

func (m *ReplyAssetList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyAssetList.Unmarshal(m, b)
}
func (m *ReplyAssetList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyAssetList.Marshal(b, m, deterministic)
}
func (m *ReplyAssetList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyAssetList.Merge(m, src)
}
func (m *ReplyAssetList) XXX_Size() int {
	return xxx_messageInfo_ReplyAssetList.Size(m)
}
func (m *ReplyAssetList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyAssetList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyAssetList proto.InternalMessageInfo

func (m *ReplyAssetList) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReplyAssetList) GetList() []*AssetInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *ReplyAssetList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterEnum("omo.msp.asset.OwnerType", OwnerType_name, OwnerType_value)
	proto.RegisterType((*AssetInfo)(nil), "omo.msp.asset.AssetInfo")
	proto.RegisterType((*ReqAssetAdd)(nil), "omo.msp.asset.ReqAssetAdd")
	proto.RegisterType((*ReqAssetSnapshot)(nil), "omo.msp.asset.ReqAssetSnapshot")
	proto.RegisterType((*ReplyAssetOne)(nil), "omo.msp.asset.ReplyAssetOne")
	proto.RegisterType((*ReqAssetList)(nil), "omo.msp.asset.ReqAssetList")
	proto.RegisterType((*ReplyAssetList)(nil), "omo.msp.asset.ReplyAssetList")
}

func init() {
	proto.RegisterFile("proto/asset/asset.proto", fileDescriptor_78e4568551c90fa4)
}

var fileDescriptor_78e4568551c90fa4 = []byte{
	// 659 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0xd1, 0x6e, 0xd3, 0x4a,
	0x10, 0x8d, 0xe3, 0xc4, 0xa9, 0x27, 0x71, 0x6e, 0xee, 0x0a, 0xc1, 0x2a, 0x80, 0xb0, 0xfc, 0x14,
	0x21, 0x14, 0xa4, 0xa0, 0x7e, 0x40, 0x0b, 0x52, 0x54, 0x09, 0x54, 0xc9, 0x85, 0x17, 0xc4, 0x8b,
	0x5b, 0x6f, 0x13, 0x4b, 0xb1, 0xd7, 0xf5, 0xae, 0x5b, 0x85, 0x2f, 0xe0, 0xbb, 0x78, 0xe3, 0x5b,
	0xf8, 0x09, 0xb4, 0xb3, 0xb6, 0xeb, 0x26, 0x76, 0xd3, 0x97, 0x6a, 0xcf, 0xcc, 0xf1, 0xd9, 0x99,
	0x73, 0xba, 0x2d, 0xbc, 0x48, 0x33, 0x2e, 0xf9, 0xfb, 0x40, 0x08, 0x26, 0xf5, 0xcf, 0x39, 0x56,
	0x88, 0xc3, 0x63, 0x3e, 0x8f, 0x45, 0x3a, 0xc7, 0xe2, 0x94, 0xd6, 0x79, 0x57, 0x3c, 0x8e, 0x79,
	0xa2, 0x89, 0xde, 0x1f, 0x13, 0xec, 0x13, 0x55, 0x3e, 0x4b, 0xae, 0x39, 0x99, 0x80, 0x99, 0x47,
	0x21, 0x35, 0x5c, 0x63, 0x66, 0xfb, 0xea, 0x48, 0x08, 0xf4, 0x92, 0x20, 0x66, 0xb4, 0x8b, 0x25,
	0x3c, 0x2b, 0x56, 0x1c, 0x1e, 0x53, 0x53, 0xb3, 0xe2, 0xf0, 0x98, 0x3c, 0x07, 0xeb, 0x9a, 0x67,
	0x71, 0x20, 0x69, 0x0f, 0x8b, 0x05, 0x22, 0x14, 0x06, 0xb7, 0x2c, 0x13, 0x11, 0x4f, 0x68, 0x1f,
	0x1b, 0x25, 0x54, 0xba, 0x22, 0xfa, 0xc9, 0xa8, 0xe5, 0x1a, 0xb3, 0x9e, 0x8f, 0x67, 0x32, 0x85,
	0xa3, 0x4d, 0x90, 0xac, 0xf2, 0x60, 0xc5, 0xe8, 0x00, 0xe9, 0x15, 0x26, 0xef, 0xa0, 0x27, 0xb7,
	0x29, 0xa3, 0x47, 0xae, 0x31, 0x1b, 0x2f, 0xe8, 0xfc, 0xc1, 0x7e, 0xf3, 0xf3, 0xbb, 0x84, 0x65,
	0x5f, 0xb7, 0x29, 0xf3, 0x91, 0x45, 0x9e, 0x41, 0x9f, 0xab, 0x12, 0xb5, 0x51, 0x46, 0x03, 0x75,
	0x67, 0xae, 0xd6, 0x03, 0xbd, 0x8b, 0x3a, 0xab, 0x09, 0xaf, 0x32, 0x16, 0x48, 0x16, 0xd2, 0xa1,
	0x6b, 0xcc, 0x4c, 0xbf, 0x84, 0xaa, 0x93, 0xa7, 0x21, 0x76, 0x46, 0xba, 0x53, 0xc0, 0xea, 0x1b,
	0x9e, 0x51, 0x47, 0x6f, 0x55, 0x40, 0xb5, 0x01, 0x4f, 0x59, 0x86, 0xad, 0xb1, 0xde, 0xa0, 0xc4,
	0x6a, 0xa6, 0xbb, 0x28, 0x94, 0x6b, 0xfa, 0x9f, 0x6b, 0xcc, 0x1c, 0x5f, 0x03, 0xe5, 0xdc, 0x9a,
	0x45, 0xab, 0xb5, 0xa4, 0x13, 0x2c, 0x17, 0x48, 0x29, 0x89, 0x24, 0x48, 0xc5, 0x9a, 0x4b, 0xfa,
	0xbf, 0x56, 0x2a, 0xb1, 0xfa, 0x46, 0xae, 0xf3, 0xf8, 0x52, 0x50, 0xe2, 0x9a, 0xca, 0x6d, 0x8d,
	0xbc, 0xbf, 0x5d, 0x18, 0xfa, 0xec, 0x06, 0xe3, 0x3c, 0x09, 0xef, 0xb3, 0x33, 0xf6, 0xb3, 0xeb,
	0x36, 0x65, 0x67, 0xb6, 0x65, 0xd7, 0x6b, 0xce, 0xae, 0xdf, 0x92, 0x9d, 0xb5, 0x93, 0x5d, 0xe9,
	0xfb, 0xa0, 0xe6, 0x7b, 0x95, 0xd0, 0x51, 0x3d, 0xa1, 0x32, 0x65, 0xfb, 0x49, 0x29, 0xd7, 0xdd,
	0x86, 0x36, 0xb7, 0x87, 0xcd, 0x6e, 0x8f, 0x5a, 0xdd, 0x76, 0x5a, 0xdd, 0x1e, 0x3f, 0x70, 0xfb,
	0x07, 0x4c, 0x4a, 0xb3, 0x2f, 0x4a, 0xee, 0xfe, 0xfb, 0xa9, 0x2b, 0x77, 0x77, 0x94, 0xeb, 0xf3,
	0x9b, 0x0f, 0xe7, 0xf7, 0x6e, 0xc0, 0xf1, 0x59, 0xba, 0xd9, 0xa2, 0xfe, 0x79, 0x82, 0x0f, 0x20,
	0x4a, 0xae, 0x39, 0x6a, 0x0f, 0xf7, 0xac, 0xa9, 0x9e, 0xb0, 0x8f, 0x2c, 0xb2, 0x00, 0x4b, 0xc8,
	0x40, 0xe6, 0x02, 0x2f, 0x1d, 0x2e, 0xa6, 0x3b, 0x7c, 0xd4, 0xbe, 0x40, 0x86, 0x5f, 0x30, 0x3d,
	0x0f, 0x46, 0xe5, 0x42, 0x9f, 0x23, 0x21, 0x55, 0x6c, 0x9b, 0x48, 0x48, 0x6a, 0xe0, 0xda, 0x78,
	0xf6, 0x7e, 0x19, 0x30, 0xbe, 0x9f, 0x0b, 0x69, 0x55, 0x92, 0xc6, 0x4e, 0x92, 0xf8, 0x71, 0xd7,
	0x35, 0x1f, 0x1f, 0x57, 0xb1, 0x6a, 0xe3, 0x9a, 0x4f, 0x1d, 0xf7, 0xad, 0x07, 0x76, 0xf5, 0x0b,
	0x41, 0x00, 0xac, 0x8b, 0x28, 0x59, 0x6d, 0xd8, 0xa4, 0x43, 0x6c, 0xe8, 0x2f, 0x33, 0x9e, 0xa7,
	0x13, 0x63, 0xf1, 0xdb, 0x84, 0x91, 0x4e, 0x88, 0x65, 0xb7, 0xd1, 0x15, 0x23, 0x9f, 0xc0, 0x3a,
	0x09, 0x43, 0xe5, 0xe7, 0xfe, 0x15, 0xd5, 0xc3, 0x99, 0xbe, 0x6a, 0xba, 0xbe, 0x4c, 0xc2, 0xeb,
	0x28, 0x95, 0xa5, 0x4e, 0xa5, 0x41, 0x25, 0x67, 0x02, 0x57, 0x3b, 0xa8, 0xf2, 0x11, 0x6c, 0x9f,
	0xc5, 0xfc, 0x96, 0x1d, 0x12, 0xa2, 0x4d, 0x42, 0xaa, 0xe3, 0x75, 0xc8, 0x12, 0x06, 0xcb, 0x22,
	0x88, 0x97, 0x2d, 0x1b, 0xa9, 0xe6, 0xf4, 0x75, 0xeb, 0x30, 0xaa, 0xed, 0x75, 0xc8, 0x19, 0xc0,
	0x92, 0xc9, 0xd3, 0x2d, 0x7a, 0xfa, 0xe8, 0x38, 0x07, 0xa5, 0xbe, 0xc0, 0xf8, 0x1b, 0xfe, 0xa9,
	0xac, 0xde, 0xc5, 0x9b, 0x96, 0xd1, 0x4a, 0xc2, 0x63, 0x2b, 0x9e, 0x3a, 0xdf, 0x87, 0xb5, 0x7f,
	0x5f, 0x97, 0x16, 0x82, 0x0f, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x1c, 0xf8, 0xac, 0x86, 0xfc,
	0x06, 0x00, 0x00,
}
