// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/asset/folder.proto

package asset

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FolderInfo struct {
	Uid                  string      `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Id                   uint64      `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64       `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64       `protobuf:"varint,4,opt,name=updated,proto3" json:"updated,omitempty"`
	Creator              string      `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string      `protobuf:"bytes,6,opt,name=operator,proto3" json:"operator,omitempty"`
	Name                 string      `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string      `protobuf:"bytes,8,opt,name=remark,proto3" json:"remark,omitempty"`
	Owner                string      `protobuf:"bytes,9,opt,name=owner,proto3" json:"owner,omitempty"`
	Parent               string      `protobuf:"bytes,10,opt,name=parent,proto3" json:"parent,omitempty"`
	Access               uint32      `protobuf:"varint,11,opt,name=access,proto3" json:"access,omitempty"`
	Cover                string      `protobuf:"bytes,12,opt,name=cover,proto3" json:"cover,omitempty"`
	Type                 uint32      `protobuf:"varint,13,opt,name=type,proto3" json:"type,omitempty"`
	Tags                 []string    `protobuf:"bytes,21,rep,name=tags,proto3" json:"tags,omitempty"`
	Users                []string    `protobuf:"bytes,22,rep,name=users,proto3" json:"users,omitempty"`
	Contents             []*PairInfo `protobuf:"bytes,31,rep,name=contents,proto3" json:"contents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *FolderInfo) Reset()         { *m = FolderInfo{} }
func (m *FolderInfo) String() string { return proto.CompactTextString(m) }
func (*FolderInfo) ProtoMessage()    {}
func (*FolderInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_77f3e9c8a788b900, []int{0}
}

func (m *FolderInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FolderInfo.Unmarshal(m, b)
}
func (m *FolderInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FolderInfo.Marshal(b, m, deterministic)
}
func (m *FolderInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FolderInfo.Merge(m, src)
}
func (m *FolderInfo) XXX_Size() int {
	return xxx_messageInfo_FolderInfo.Size(m)
}
func (m *FolderInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FolderInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FolderInfo proto.InternalMessageInfo

func (m *FolderInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *FolderInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FolderInfo) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *FolderInfo) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *FolderInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *FolderInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *FolderInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FolderInfo) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *FolderInfo) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *FolderInfo) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *FolderInfo) GetAccess() uint32 {
	if m != nil {
		return m.Access
	}
	return 0
}

func (m *FolderInfo) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *FolderInfo) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *FolderInfo) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *FolderInfo) GetUsers() []string {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *FolderInfo) GetContents() []*PairInfo {
	if m != nil {
		return m.Contents
	}
	return nil
}

type ReqFolderAdd struct {
	Name                 string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string      `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark,omitempty"`
	Operator             string      `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	Owner                string      `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	Parent               string      `protobuf:"bytes,5,opt,name=parent,proto3" json:"parent,omitempty"`
	Cover                string      `protobuf:"bytes,6,opt,name=cover,proto3" json:"cover,omitempty"`
	Tags                 []string    `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	Users                []string    `protobuf:"bytes,11,rep,name=users,proto3" json:"users,omitempty"`
	Contents             []*PairInfo `protobuf:"bytes,12,rep,name=contents,proto3" json:"contents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ReqFolderAdd) Reset()         { *m = ReqFolderAdd{} }
func (m *ReqFolderAdd) String() string { return proto.CompactTextString(m) }
func (*ReqFolderAdd) ProtoMessage()    {}
func (*ReqFolderAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_77f3e9c8a788b900, []int{1}
}

func (m *ReqFolderAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqFolderAdd.Unmarshal(m, b)
}
func (m *ReqFolderAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqFolderAdd.Marshal(b, m, deterministic)
}
func (m *ReqFolderAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqFolderAdd.Merge(m, src)
}
func (m *ReqFolderAdd) XXX_Size() int {
	return xxx_messageInfo_ReqFolderAdd.Size(m)
}
func (m *ReqFolderAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqFolderAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqFolderAdd proto.InternalMessageInfo

func (m *ReqFolderAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqFolderAdd) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqFolderAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqFolderAdd) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReqFolderAdd) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *ReqFolderAdd) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *ReqFolderAdd) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *ReqFolderAdd) GetUsers() []string {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *ReqFolderAdd) GetContents() []*PairInfo {
	if m != nil {
		return m.Contents
	}
	return nil
}

type ReqFolderUpdate struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Operator             string   `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	Parent               string   `protobuf:"bytes,5,opt,name=parent,proto3" json:"parent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqFolderUpdate) Reset()         { *m = ReqFolderUpdate{} }
func (m *ReqFolderUpdate) String() string { return proto.CompactTextString(m) }
func (*ReqFolderUpdate) ProtoMessage()    {}
func (*ReqFolderUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_77f3e9c8a788b900, []int{2}
}

func (m *ReqFolderUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqFolderUpdate.Unmarshal(m, b)
}
func (m *ReqFolderUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqFolderUpdate.Marshal(b, m, deterministic)
}
func (m *ReqFolderUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqFolderUpdate.Merge(m, src)
}
func (m *ReqFolderUpdate) XXX_Size() int {
	return xxx_messageInfo_ReqFolderUpdate.Size(m)
}
func (m *ReqFolderUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqFolderUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ReqFolderUpdate proto.InternalMessageInfo

func (m *ReqFolderUpdate) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqFolderUpdate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqFolderUpdate) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqFolderUpdate) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqFolderUpdate) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

type ReqFolderContents struct {
	Uid                  string      `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Operator             string      `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Contents             []*PairInfo `protobuf:"bytes,11,rep,name=contents,proto3" json:"contents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ReqFolderContents) Reset()         { *m = ReqFolderContents{} }
func (m *ReqFolderContents) String() string { return proto.CompactTextString(m) }
func (*ReqFolderContents) ProtoMessage()    {}
func (*ReqFolderContents) Descriptor() ([]byte, []int) {
	return fileDescriptor_77f3e9c8a788b900, []int{3}
}

func (m *ReqFolderContents) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqFolderContents.Unmarshal(m, b)
}
func (m *ReqFolderContents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqFolderContents.Marshal(b, m, deterministic)
}
func (m *ReqFolderContents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqFolderContents.Merge(m, src)
}
func (m *ReqFolderContents) XXX_Size() int {
	return xxx_messageInfo_ReqFolderContents.Size(m)
}
func (m *ReqFolderContents) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqFolderContents.DiscardUnknown(m)
}

var xxx_messageInfo_ReqFolderContents proto.InternalMessageInfo

func (m *ReqFolderContents) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqFolderContents) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqFolderContents) GetContents() []*PairInfo {
	if m != nil {
		return m.Contents
	}
	return nil
}

type ReplyFolderInfo struct {
	Status               *ReplyStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Info                 *FolderInfo  `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyFolderInfo) Reset()         { *m = ReplyFolderInfo{} }
func (m *ReplyFolderInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyFolderInfo) ProtoMessage()    {}
func (*ReplyFolderInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_77f3e9c8a788b900, []int{4}
}

func (m *ReplyFolderInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyFolderInfo.Unmarshal(m, b)
}
func (m *ReplyFolderInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyFolderInfo.Marshal(b, m, deterministic)
}
func (m *ReplyFolderInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyFolderInfo.Merge(m, src)
}
func (m *ReplyFolderInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyFolderInfo.Size(m)
}
func (m *ReplyFolderInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyFolderInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyFolderInfo proto.InternalMessageInfo

func (m *ReplyFolderInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyFolderInfo) GetInfo() *FolderInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type ReplyFolderList struct {
	Status               *ReplyStatus  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	List                 []*FolderInfo `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ReplyFolderList) Reset()         { *m = ReplyFolderList{} }
func (m *ReplyFolderList) String() string { return proto.CompactTextString(m) }
func (*ReplyFolderList) ProtoMessage()    {}
func (*ReplyFolderList) Descriptor() ([]byte, []int) {
	return fileDescriptor_77f3e9c8a788b900, []int{5}
}

func (m *ReplyFolderList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyFolderList.Unmarshal(m, b)
}
func (m *ReplyFolderList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyFolderList.Marshal(b, m, deterministic)
}
func (m *ReplyFolderList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyFolderList.Merge(m, src)
}
func (m *ReplyFolderList) XXX_Size() int {
	return xxx_messageInfo_ReplyFolderList.Size(m)
}
func (m *ReplyFolderList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyFolderList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyFolderList proto.InternalMessageInfo

func (m *ReplyFolderList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyFolderList) GetList() []*FolderInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*FolderInfo)(nil), "omo.msp.asset.FolderInfo")
	proto.RegisterType((*ReqFolderAdd)(nil), "omo.msp.asset.ReqFolderAdd")
	proto.RegisterType((*ReqFolderUpdate)(nil), "omo.msp.asset.ReqFolderUpdate")
	proto.RegisterType((*ReqFolderContents)(nil), "omo.msp.asset.ReqFolderContents")
	proto.RegisterType((*ReplyFolderInfo)(nil), "omo.msp.asset.ReplyFolderInfo")
	proto.RegisterType((*ReplyFolderList)(nil), "omo.msp.asset.ReplyFolderList")
}

func init() {
	proto.RegisterFile("proto/asset/folder.proto", fileDescriptor_77f3e9c8a788b900)
}

var fileDescriptor_77f3e9c8a788b900 = []byte{
	// 631 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0x4f, 0x6f, 0xd3, 0x4e,
	0x10, 0xad, 0xff, 0xd4, 0x6d, 0xc7, 0x49, 0x7f, 0x3f, 0x56, 0x50, 0x96, 0x00, 0xc5, 0xca, 0x29,
	0x17, 0x52, 0x29, 0xfd, 0x04, 0x6d, 0xa5, 0x06, 0x10, 0x15, 0xc8, 0x85, 0x0b, 0x37, 0x63, 0x4f,
	0x91, 0x45, 0xec, 0x75, 0xbd, 0x9b, 0xa0, 0x9e, 0xf9, 0x08, 0x7c, 0x50, 0xce, 0xdc, 0xd0, 0xce,
	0x3a, 0x6e, 0xe2, 0xda, 0x6d, 0xc4, 0x6d, 0x67, 0xe6, 0xed, 0xdb, 0xf7, 0xde, 0xae, 0x65, 0xe0,
	0x45, 0x29, 0x94, 0x38, 0x8a, 0xa4, 0x44, 0x75, 0x74, 0x25, 0x66, 0x09, 0x96, 0x63, 0x6a, 0xb1,
	0xbe, 0xc8, 0xc4, 0x38, 0x93, 0xc5, 0x98, 0x66, 0x83, 0x35, 0x60, 0x2c, 0xb2, 0x4c, 0xe4, 0x06,
	0x38, 0xfc, 0xe5, 0x00, 0x9c, 0xd3, 0xce, 0xb7, 0xf9, 0x95, 0x60, 0xff, 0x83, 0x33, 0x4f, 0x13,
	0x6e, 0x05, 0xd6, 0x68, 0x2f, 0xd4, 0x4b, 0xb6, 0x0f, 0x76, 0x9a, 0x70, 0x3b, 0xb0, 0x46, 0x6e,
	0x68, 0xa7, 0x09, 0xe3, 0xb0, 0x13, 0x97, 0x18, 0x29, 0x4c, 0xb8, 0x13, 0x58, 0x23, 0x27, 0x5c,
	0x96, 0x7a, 0x32, 0x2f, 0x12, 0x9a, 0xb8, 0x66, 0x52, 0x95, 0xf5, 0x1e, 0x51, 0xf2, 0x6d, 0x62,
	0x5e, 0x96, 0x6c, 0x00, 0xbb, 0xa2, 0xc0, 0x92, 0x46, 0x1e, 0x8d, 0xea, 0x9a, 0x31, 0x70, 0xf3,
	0x28, 0x43, 0xbe, 0x43, 0x7d, 0x5a, 0xb3, 0x03, 0xf0, 0x4a, 0xcc, 0xa2, 0xf2, 0x3b, 0xdf, 0xa5,
	0x6e, 0x55, 0xb1, 0xc7, 0xb0, 0x2d, 0x7e, 0xe4, 0x58, 0xf2, 0x3d, 0x6a, 0x9b, 0x42, 0xa3, 0x8b,
	0xa8, 0xc4, 0x5c, 0x71, 0x30, 0x68, 0x53, 0xe9, 0x7e, 0x14, 0xc7, 0x28, 0x25, 0xf7, 0x03, 0x6b,
	0xd4, 0x0f, 0xab, 0x4a, 0xb3, 0xc4, 0x62, 0x81, 0x25, 0xef, 0x19, 0x16, 0x2a, 0xb4, 0x0e, 0x75,
	0x53, 0x20, 0xef, 0x13, 0x96, 0xd6, 0xd4, 0x8b, 0xbe, 0x49, 0xfe, 0x24, 0x70, 0xb4, 0x36, 0xbd,
	0xd6, 0xbb, 0xe7, 0x12, 0x4b, 0xc9, 0x0f, 0xa8, 0x69, 0x0a, 0x76, 0x0c, 0xbb, 0xb1, 0xc8, 0x15,
	0xe6, 0x4a, 0xf2, 0x57, 0x81, 0x33, 0xf2, 0x27, 0x4f, 0xc7, 0x6b, 0x97, 0x33, 0xfe, 0x18, 0xa5,
	0x14, 0x7e, 0x58, 0x03, 0x87, 0x7f, 0x2c, 0xe8, 0x85, 0x78, 0x6d, 0x2e, 0xe6, 0x24, 0x49, 0xea,
	0x2c, 0xac, 0xd6, 0x2c, 0xec, 0xb5, 0x2c, 0x56, 0x33, 0x75, 0x1a, 0x99, 0xd6, 0x39, 0xb9, 0xed,
	0x39, 0x6d, 0xaf, 0xe5, 0x54, 0xe7, 0xe1, 0x35, 0xf3, 0xd0, 0xde, 0xa1, 0xcd, 0xbb, 0xdf, 0xe5,
	0xbd, 0xb7, 0xa9, 0xf7, 0x9f, 0x16, 0xfc, 0x57, 0x7b, 0xff, 0x4c, 0x2f, 0xa8, 0xe5, 0x59, 0x2e,
	0x03, 0xb1, 0x5b, 0x03, 0x71, 0x3a, 0x03, 0x71, 0x1b, 0x81, 0x74, 0x58, 0x1f, 0x2e, 0xe0, 0x51,
	0x2d, 0xe2, 0xac, 0x92, 0xd6, 0x22, 0x63, 0x95, 0xda, 0x6e, 0x50, 0xaf, 0xba, 0xf7, 0x37, 0x75,
	0xaf, 0xb4, 0xf9, 0x62, 0x76, 0xb3, 0xf2, 0x4d, 0x4e, 0xc0, 0x93, 0x2a, 0x52, 0x73, 0x49, 0x07,
	0xfb, 0x93, 0x41, 0x83, 0x85, 0xf0, 0x97, 0x84, 0x08, 0x2b, 0x24, 0x7b, 0x0d, 0x6e, 0x9a, 0x5f,
	0x09, 0xd2, 0xe4, 0x4f, 0x9e, 0x35, 0x76, 0xdc, 0x92, 0x87, 0x04, 0x6b, 0x9c, 0xfa, 0x3e, 0x95,
	0xea, 0x5f, 0x4f, 0x9d, 0xa5, 0x52, 0x71, 0x9b, 0xdc, 0xde, 0x77, 0xaa, 0x86, 0x4d, 0x7e, 0xbb,
	0xd0, 0x37, 0xcd, 0x4b, 0x2c, 0x17, 0x69, 0x8c, 0x6c, 0x0a, 0xde, 0x49, 0x92, 0x7c, 0xc8, 0x91,
	0x3d, 0xbf, 0x73, 0xdc, 0xed, 0xd7, 0x30, 0x38, 0x6c, 0xd3, 0x72, 0x4b, 0x3f, 0xdc, 0x62, 0x6f,
	0x00, 0xcc, 0xd3, 0x39, 0x8d, 0x24, 0xb2, 0xc3, 0x2e, 0x32, 0x83, 0x19, 0xf0, 0x36, 0xbe, 0x8a,
	0xe9, 0x0c, 0xf6, 0x42, 0xcc, 0xc4, 0x02, 0xb5, 0xaa, 0xbb, 0x21, 0x5c, 0xcf, 0x51, 0x2a, 0x0d,
	0xbd, 0x97, 0xe4, 0x1c, 0xbc, 0x29, 0xaa, 0x87, 0x18, 0x1e, 0xb6, 0x75, 0x01, 0xbd, 0x29, 0x2a,
	0x9d, 0x7a, 0x2a, 0x55, 0x1a, 0xb3, 0x17, 0xed, 0x6c, 0xe7, 0xe9, 0x4c, 0x61, 0x39, 0x78, 0xd9,
	0x75, 0x65, 0xb4, 0x79, 0xb8, 0xc5, 0x3e, 0xc1, 0xbe, 0x49, 0xa0, 0x7e, 0xe1, 0x41, 0x57, 0x52,
	0x4b, 0xc4, 0x06, 0x22, 0xdf, 0x2d, 0x59, 0x4f, 0x6f, 0x8c, 0x90, 0x2e, 0x99, 0x1b, 0xa4, 0x7f,
	0x01, 0xfe, 0x14, 0xd5, 0x43, 0x44, 0x95, 0xdf, 0x7b, 0xa4, 0xe9, 0x27, 0x3d, 0xdc, 0x3a, 0xed,
	0x7f, 0xf1, 0x57, 0xfe, 0x84, 0x5f, 0x3d, 0x2a, 0x8e, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x3f,
	0x89, 0xef, 0xc2, 0x48, 0x07, 0x00, 0x00,
}
