// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/asset/folder.proto

package asset

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for FolderService service

type FolderService interface {
	AddOne(ctx context.Context, in *ReqFolderAdd, opts ...client.CallOption) (*ReplyFolderInfo, error)
	UpdateBase(ctx context.Context, in *ReqFolderUpdate, opts ...client.CallOption) (*ReplyInfo, error)
	RemoveOne(ctx context.Context, in *RequestInfo, opts ...client.CallOption) (*ReplyInfo, error)
	GetOne(ctx context.Context, in *RequestInfo, opts ...client.CallOption) (*ReplyFolderInfo, error)
	GetStatistic(ctx context.Context, in *RequestFilter, opts ...client.CallOption) (*ReplyStatistic, error)
	UpdateContents(ctx context.Context, in *ReqFolderContents, opts ...client.CallOption) (*ReplyFolderInfo, error)
	UpdateByFilter(ctx context.Context, in *RequestUpdate, opts ...client.CallOption) (*ReplyInfo, error)
	GetByFilter(ctx context.Context, in *RequestFilter, opts ...client.CallOption) (*ReplyFolderList, error)
}

type folderService struct {
	c    client.Client
	name string
}

func NewFolderService(name string, c client.Client) FolderService {
	return &folderService{
		c:    c,
		name: name,
	}
}

func (c *folderService) AddOne(ctx context.Context, in *ReqFolderAdd, opts ...client.CallOption) (*ReplyFolderInfo, error) {
	req := c.c.NewRequest(c.name, "FolderService.AddOne", in)
	out := new(ReplyFolderInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *folderService) UpdateBase(ctx context.Context, in *ReqFolderUpdate, opts ...client.CallOption) (*ReplyInfo, error) {
	req := c.c.NewRequest(c.name, "FolderService.UpdateBase", in)
	out := new(ReplyInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *folderService) RemoveOne(ctx context.Context, in *RequestInfo, opts ...client.CallOption) (*ReplyInfo, error) {
	req := c.c.NewRequest(c.name, "FolderService.RemoveOne", in)
	out := new(ReplyInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *folderService) GetOne(ctx context.Context, in *RequestInfo, opts ...client.CallOption) (*ReplyFolderInfo, error) {
	req := c.c.NewRequest(c.name, "FolderService.GetOne", in)
	out := new(ReplyFolderInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *folderService) GetStatistic(ctx context.Context, in *RequestFilter, opts ...client.CallOption) (*ReplyStatistic, error) {
	req := c.c.NewRequest(c.name, "FolderService.GetStatistic", in)
	out := new(ReplyStatistic)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *folderService) UpdateContents(ctx context.Context, in *ReqFolderContents, opts ...client.CallOption) (*ReplyFolderInfo, error) {
	req := c.c.NewRequest(c.name, "FolderService.UpdateContents", in)
	out := new(ReplyFolderInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *folderService) UpdateByFilter(ctx context.Context, in *RequestUpdate, opts ...client.CallOption) (*ReplyInfo, error) {
	req := c.c.NewRequest(c.name, "FolderService.UpdateByFilter", in)
	out := new(ReplyInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *folderService) GetByFilter(ctx context.Context, in *RequestFilter, opts ...client.CallOption) (*ReplyFolderList, error) {
	req := c.c.NewRequest(c.name, "FolderService.GetByFilter", in)
	out := new(ReplyFolderList)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FolderService service

type FolderServiceHandler interface {
	AddOne(context.Context, *ReqFolderAdd, *ReplyFolderInfo) error
	UpdateBase(context.Context, *ReqFolderUpdate, *ReplyInfo) error
	RemoveOne(context.Context, *RequestInfo, *ReplyInfo) error
	GetOne(context.Context, *RequestInfo, *ReplyFolderInfo) error
	GetStatistic(context.Context, *RequestFilter, *ReplyStatistic) error
	UpdateContents(context.Context, *ReqFolderContents, *ReplyFolderInfo) error
	UpdateByFilter(context.Context, *RequestUpdate, *ReplyInfo) error
	GetByFilter(context.Context, *RequestFilter, *ReplyFolderList) error
}

func RegisterFolderServiceHandler(s server.Server, hdlr FolderServiceHandler, opts ...server.HandlerOption) error {
	type folderService interface {
		AddOne(ctx context.Context, in *ReqFolderAdd, out *ReplyFolderInfo) error
		UpdateBase(ctx context.Context, in *ReqFolderUpdate, out *ReplyInfo) error
		RemoveOne(ctx context.Context, in *RequestInfo, out *ReplyInfo) error
		GetOne(ctx context.Context, in *RequestInfo, out *ReplyFolderInfo) error
		GetStatistic(ctx context.Context, in *RequestFilter, out *ReplyStatistic) error
		UpdateContents(ctx context.Context, in *ReqFolderContents, out *ReplyFolderInfo) error
		UpdateByFilter(ctx context.Context, in *RequestUpdate, out *ReplyInfo) error
		GetByFilter(ctx context.Context, in *RequestFilter, out *ReplyFolderList) error
	}
	type FolderService struct {
		folderService
	}
	h := &folderServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&FolderService{h}, opts...))
}

type folderServiceHandler struct {
	FolderServiceHandler
}

func (h *folderServiceHandler) AddOne(ctx context.Context, in *ReqFolderAdd, out *ReplyFolderInfo) error {
	return h.FolderServiceHandler.AddOne(ctx, in, out)
}

func (h *folderServiceHandler) UpdateBase(ctx context.Context, in *ReqFolderUpdate, out *ReplyInfo) error {
	return h.FolderServiceHandler.UpdateBase(ctx, in, out)
}

func (h *folderServiceHandler) RemoveOne(ctx context.Context, in *RequestInfo, out *ReplyInfo) error {
	return h.FolderServiceHandler.RemoveOne(ctx, in, out)
}

func (h *folderServiceHandler) GetOne(ctx context.Context, in *RequestInfo, out *ReplyFolderInfo) error {
	return h.FolderServiceHandler.GetOne(ctx, in, out)
}

func (h *folderServiceHandler) GetStatistic(ctx context.Context, in *RequestFilter, out *ReplyStatistic) error {
	return h.FolderServiceHandler.GetStatistic(ctx, in, out)
}

func (h *folderServiceHandler) UpdateContents(ctx context.Context, in *ReqFolderContents, out *ReplyFolderInfo) error {
	return h.FolderServiceHandler.UpdateContents(ctx, in, out)
}

func (h *folderServiceHandler) UpdateByFilter(ctx context.Context, in *RequestUpdate, out *ReplyInfo) error {
	return h.FolderServiceHandler.UpdateByFilter(ctx, in, out)
}

func (h *folderServiceHandler) GetByFilter(ctx context.Context, in *RequestFilter, out *ReplyFolderList) error {
	return h.FolderServiceHandler.GetByFilter(ctx, in, out)
}
