// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/asset/label.proto

package asset

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LabelInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Created              int64    `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64    `protobuf:"varint,3,opt,name=updated,proto3" json:"updated,omitempty"`
	Creator              string   `protobuf:"bytes,4,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string   `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	Name                 string   `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Scene                string   `protobuf:"bytes,7,opt,name=scene,proto3" json:"scene,omitempty"`
	Remark               string   `protobuf:"bytes,8,opt,name=remark,proto3" json:"remark,omitempty"`
	Type                 uint32   `protobuf:"varint,9,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LabelInfo) Reset()         { *m = LabelInfo{} }
func (m *LabelInfo) String() string { return proto.CompactTextString(m) }
func (*LabelInfo) ProtoMessage()    {}
func (*LabelInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_223c644942f876ab, []int{0}
}

func (m *LabelInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LabelInfo.Unmarshal(m, b)
}
func (m *LabelInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LabelInfo.Marshal(b, m, deterministic)
}
func (m *LabelInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LabelInfo.Merge(m, src)
}
func (m *LabelInfo) XXX_Size() int {
	return xxx_messageInfo_LabelInfo.Size(m)
}
func (m *LabelInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LabelInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LabelInfo proto.InternalMessageInfo

func (m *LabelInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *LabelInfo) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *LabelInfo) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *LabelInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *LabelInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *LabelInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LabelInfo) GetScene() string {
	if m != nil {
		return m.Scene
	}
	return ""
}

func (m *LabelInfo) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *LabelInfo) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

type ReqLabelAdd struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Scene                string   `protobuf:"bytes,2,opt,name=scene,proto3" json:"scene,omitempty"`
	Remark               string   `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Operator             string   `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	Type                 uint32   `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqLabelAdd) Reset()         { *m = ReqLabelAdd{} }
func (m *ReqLabelAdd) String() string { return proto.CompactTextString(m) }
func (*ReqLabelAdd) ProtoMessage()    {}
func (*ReqLabelAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_223c644942f876ab, []int{1}
}

func (m *ReqLabelAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqLabelAdd.Unmarshal(m, b)
}
func (m *ReqLabelAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqLabelAdd.Marshal(b, m, deterministic)
}
func (m *ReqLabelAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqLabelAdd.Merge(m, src)
}
func (m *ReqLabelAdd) XXX_Size() int {
	return xxx_messageInfo_ReqLabelAdd.Size(m)
}
func (m *ReqLabelAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqLabelAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqLabelAdd proto.InternalMessageInfo

func (m *ReqLabelAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqLabelAdd) GetScene() string {
	if m != nil {
		return m.Scene
	}
	return ""
}

func (m *ReqLabelAdd) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqLabelAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqLabelAdd) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

type ReplyLabelInfo struct {
	Status               *ReplyStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Info                 *LabelInfo   `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyLabelInfo) Reset()         { *m = ReplyLabelInfo{} }
func (m *ReplyLabelInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyLabelInfo) ProtoMessage()    {}
func (*ReplyLabelInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_223c644942f876ab, []int{2}
}

func (m *ReplyLabelInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyLabelInfo.Unmarshal(m, b)
}
func (m *ReplyLabelInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyLabelInfo.Marshal(b, m, deterministic)
}
func (m *ReplyLabelInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyLabelInfo.Merge(m, src)
}
func (m *ReplyLabelInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyLabelInfo.Size(m)
}
func (m *ReplyLabelInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyLabelInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyLabelInfo proto.InternalMessageInfo

func (m *ReplyLabelInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyLabelInfo) GetInfo() *LabelInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type ReplyLabelList struct {
	Status               *ReplyStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	List                 []*LabelInfo `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyLabelList) Reset()         { *m = ReplyLabelList{} }
func (m *ReplyLabelList) String() string { return proto.CompactTextString(m) }
func (*ReplyLabelList) ProtoMessage()    {}
func (*ReplyLabelList) Descriptor() ([]byte, []int) {
	return fileDescriptor_223c644942f876ab, []int{3}
}

func (m *ReplyLabelList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyLabelList.Unmarshal(m, b)
}
func (m *ReplyLabelList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyLabelList.Marshal(b, m, deterministic)
}
func (m *ReplyLabelList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyLabelList.Merge(m, src)
}
func (m *ReplyLabelList) XXX_Size() int {
	return xxx_messageInfo_ReplyLabelList.Size(m)
}
func (m *ReplyLabelList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyLabelList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyLabelList proto.InternalMessageInfo

func (m *ReplyLabelList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyLabelList) GetList() []*LabelInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*LabelInfo)(nil), "omo.msp.asset.LabelInfo")
	proto.RegisterType((*ReqLabelAdd)(nil), "omo.msp.asset.ReqLabelAdd")
	proto.RegisterType((*ReplyLabelInfo)(nil), "omo.msp.asset.ReplyLabelInfo")
	proto.RegisterType((*ReplyLabelList)(nil), "omo.msp.asset.ReplyLabelList")
}

func init() {
	proto.RegisterFile("proto/asset/label.proto", fileDescriptor_223c644942f876ab)
}

var fileDescriptor_223c644942f876ab = []byte{
	// 438 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0x51, 0x8b, 0xd3, 0x40,
	0x10, 0xc7, 0x9b, 0xa6, 0xcd, 0x5d, 0x27, 0xd7, 0x43, 0x16, 0xd1, 0xa5, 0x28, 0x94, 0x3c, 0xf5,
	0x41, 0x72, 0x50, 0x3f, 0xc1, 0x9d, 0x68, 0x51, 0x2a, 0xc2, 0x1e, 0xbe, 0xf8, 0x96, 0x4b, 0xe6,
	0x60, 0x31, 0xc9, 0xc6, 0xdd, 0xcd, 0x41, 0x9f, 0xfc, 0x7e, 0x7e, 0x07, 0xbf, 0x8b, 0xec, 0x24,
	0x17, 0x53, 0x2f, 0xb6, 0xd0, 0xb7, 0x9d, 0x99, 0xff, 0xfc, 0xfe, 0x33, 0x9d, 0x12, 0x78, 0x59,
	0x69, 0x65, 0xd5, 0x55, 0x62, 0x0c, 0xda, 0xab, 0x3c, 0xb9, 0xc3, 0x3c, 0xa6, 0x0c, 0x9b, 0xab,
	0x42, 0xc5, 0x85, 0xa9, 0x62, 0x2a, 0x2d, 0x78, 0x5f, 0x97, 0xaa, 0xa2, 0x50, 0x65, 0x23, 0x8c,
	0x7e, 0x7b, 0x30, 0xdb, 0xba, 0xc6, 0x8f, 0xe5, 0xbd, 0x62, 0xcf, 0xc0, 0xaf, 0x65, 0xc6, 0xbd,
	0xa5, 0xb7, 0x9a, 0x09, 0xf7, 0x64, 0x1c, 0xce, 0x52, 0x8d, 0x89, 0xc5, 0x8c, 0x8f, 0x97, 0xde,
	0xca, 0x17, 0x8f, 0xa1, 0xab, 0xd4, 0x55, 0x46, 0x15, 0xbf, 0xa9, 0xb4, 0x61, 0xd7, 0xa3, 0x34,
	0x9f, 0x10, 0xe9, 0x31, 0x64, 0x0b, 0x38, 0x57, 0x15, 0x6a, 0x2a, 0x4d, 0xa9, 0xd4, 0xc5, 0x8c,
	0xc1, 0xa4, 0x4c, 0x0a, 0xe4, 0x01, 0xe5, 0xe9, 0xcd, 0x9e, 0xc3, 0xd4, 0xa4, 0x58, 0x22, 0x3f,
	0xa3, 0x64, 0x13, 0xb0, 0x17, 0x10, 0x68, 0x2c, 0x12, 0xfd, 0x9d, 0x9f, 0x53, 0xba, 0x8d, 0x1c,
	0xc1, 0xee, 0x2a, 0xe4, 0xb3, 0xa5, 0xb7, 0x9a, 0x0b, 0x7a, 0x47, 0x3f, 0x21, 0x14, 0xf8, 0x83,
	0x36, 0xbc, 0xce, 0xb2, 0xce, 0xc4, 0x1b, 0x32, 0x19, 0x0f, 0x9b, 0xf8, 0x7b, 0x26, 0xfd, 0x15,
	0x26, 0x4f, 0x57, 0xa0, 0x01, 0xa6, 0xbd, 0x01, 0x34, 0x5c, 0x0a, 0xac, 0xf2, 0xdd, 0xdf, 0x1f,
	0x79, 0x0d, 0x81, 0xb1, 0x89, 0xad, 0x0d, 0x4d, 0x11, 0xae, 0x17, 0xf1, 0xde, 0xb1, 0x62, 0x92,
	0xdf, 0x92, 0x42, 0xb4, 0x4a, 0xf6, 0x06, 0x26, 0xb2, 0xbc, 0x57, 0x34, 0x62, 0xb8, 0xe6, 0xff,
	0x74, 0x74, 0x6c, 0x41, 0xaa, 0x7d, 0xcf, 0xad, 0x34, 0xf6, 0x54, 0xcf, 0x5c, 0x1a, 0xcb, 0xc7,
	0x4b, 0xff, 0xb0, 0xa7, 0x53, 0xad, 0x7f, 0xf9, 0x70, 0x41, 0xb9, 0x5b, 0xd4, 0x0f, 0x32, 0x45,
	0xf6, 0x1e, 0x82, 0xeb, 0x2c, 0xfb, 0x52, 0x22, 0x7b, 0x6a, 0xd6, 0x1d, 0x64, 0xf1, 0x7a, 0x68,
	0x90, 0x8e, 0x1d, 0x8d, 0x1c, 0x66, 0x83, 0xf6, 0x3f, 0x98, 0x1a, 0x8d, 0x75, 0xba, 0xe3, 0x98,
	0x77, 0x30, 0x13, 0x58, 0xa8, 0x07, 0x3c, 0x46, 0xe2, 0x43, 0xa4, 0x16, 0xf2, 0x09, 0x2e, 0xbf,
	0xd2, 0x7f, 0xfc, 0x66, 0xf7, 0x41, 0xe6, 0x16, 0x35, 0x7b, 0x35, 0x4c, 0x6a, 0x54, 0x07, 0x59,
	0x5b, 0x08, 0x37, 0x68, 0x8f, 0x81, 0x9a, 0xea, 0x81, 0xf5, 0xdc, 0x75, 0xa3, 0x11, 0xfb, 0x0c,
	0x17, 0x1b, 0xb4, 0xee, 0x80, 0xd2, 0x58, 0x99, 0x9e, 0x82, 0xeb, 0x9a, 0xa3, 0xd1, 0xcd, 0xfc,
	0x5b, 0xd8, 0xfb, 0x62, 0xdc, 0x05, 0x14, 0xbc, 0xfd, 0x13, 0x00, 0x00, 0xff, 0xff, 0xbc, 0x6a,
	0xc2, 0x32, 0x6f, 0x04, 0x00, 0x00,
}
